/**
 * =================================================================
 * APARATO: GENERATED TYPES MIRROR (V21.0 - SILICON SYNERGY)
 * CLASIFICACIÓN: INFRASTRUCTURE BRIDGE (ESTRATO L4)
 * RESPONSABILIDAD: ESPEJO DE TIPOS RUST PARA EL CLIENTE TYPESCRIPT
 *
 * VISION HIPER-HOLÍSTICA 2026:
 * 1. HARDWARE ALIGNMENT: Inyección de 'supports_avx2' en HardwareStats para
 *    resolver el error de compilación en el HUD de Integridad (L5).
 * 2. CONTRACT SYMMETRY: Sincronización de 'RealTimeEvent' con el flujo unificado
 *    del Panóptico (SystemLog, ArchivalDrift, InfrastructureReport).
 * 3. TYPE SOVEREIGNTY: Ajuste de magnitudes numéricas a 'number' para
 *    compatibilidad con el motor reactivo de React 19.
 * 4. HYGIENE: Erradicación de comentarios legacy y marcadores de generación obsoletos.
 *
 * # Mathematical Proof (Binary Parity):
 * Este artefacto garantiza que los bytes deserializados por el NeuralCodec
 * mapeen exactamente a las direcciones de memoria esperadas por los componentes
 * visuales, eliminando excepciones de puntero nulo en runtime.
 * =================================================================
 */

/* Generated by typeshare 1.13.4 - Manually Leveled for Silicon Sovereignty */

/** Reporte final certificado de una misión de búsqueda inmutable. */
export interface AuditReport {
	job_mission_identifier: string;
	worker_node_identifier: string;
	total_wallets_audited: string;
	execution_duration_milliseconds: number;
	final_mission_status: string;
	audit_footprint_checkpoint: string;
	completed_at_timestamp: string;
	average_computational_efficiency: number;
	/** Firma técnica del silicio utilizado (ej: ELITE_SIMD_ADX). */
	hardware_acceleration_signature: string;
}

/** Estado del Escudo de Baneo basado en densidad de red. */
export interface BanShieldStatus {
	identities_in_vault: number;
	safe_node_capacity: number;
	is_ignition_authorized: boolean;
	restriction_reason?: string;
}

/** Representa una colisión exitosa en el espacio secp256k1. */
export interface Finding {
	address: string;
	private_key_wif: string;
	source_entropy: string;
	wallet_type: string;
	found_by_worker: string;
	job_id?: string;
	detected_at: string;
}

/**
 * Telemetría detallada de hardware de un nodo individual.
 * ✅ RESOLUCIÓN ERROR COMPILACIÓN L5: Inyección de supports_avx2.
 */
export interface HardwareStats {
	cpu_frequency_megahertz: number;
	cpu_load_percentage: number;
	cpu_temperature_celsius: number;
	ram_usage_megabytes: number;
	core_count: number;
	is_thermal_throttling_active: boolean;
	/** Capacidad de aceleración vectorial detectada en el worker. */
	supports_avx2: boolean;
}

/** Solicitud de misión enviada por el worker (Handshake Táctico). */
export interface NodeHardwareCapacity {
	ram_available_mb: number;
	cpu_cores: number;
	supports_avx2: boolean;
}

export interface MissionRequestPayload {
	worker_id: string;
	hardware_capacity: NodeHardwareCapacity;
}

/** Registro de navegación del automatizador C2 (Sentinel). */
export interface ProvisioningLog {
	node_index: number;
	message: string;
	level: string;
	timestamp: string;
}

/** Estructura de Log Unificado para el Proyecto Panóptico. */
export interface SystemLog {
	id: string;
	timestamp: string;
	stratum: string;
	severity: string;
	message: string;
	metadata?: Record<string, unknown>;
	trace_id?: string;
}

/** Reporte de integridad de subsistemas internos. */
export interface SystemIntegrityReport {
	apparatus_name: string;
	status: "OPERATIONAL" | "DEGRADED" | "CRITICAL";
	metrics: Record<string, unknown>;
	detected_at_timestamp: string;
}

/** Métricas agregadas del enjambre (System Pulse). */
export interface SystemMetrics {
	active_nodes_count: number;
	cumulative_global_hashrate: number;
	active_missions_in_flight: number;
	timestamp_ms: number;
}

export type SearchStrategy =
	| { strategy_type: "Sequential", parameters: {
	start_index_hexadecimal: string;
	end_index_hexadecimal: string;
}}
	| { strategy_type: "SatoshiWindowsXpForensic", parameters: {
	scenario_template_identifier: string;
	uptime_seconds_start: number;
	uptime_seconds_end: number;
	hardware_clock_frequency: number;
}}
	| { strategy_type: "AndroidLcgForensic", parameters: {
	seed_range_start: number;
	seed_range_end: number;
}}
	| { strategy_type: "KangarooLambda", parameters: {
	target_public_key_hexadecimal: string;
	range_width_max: number;
}}
	| { strategy_type: "Dictionary", parameters: {
	dataset_resource_locator: string;
	processing_batch_size: number;
}};

export enum TargetStrata {
	SatoshiEra = "SatoshiEra",
	VulnerableLegacy = "VulnerableLegacy",
	StandardLegacy = "StandardLegacy",
	FullTacticalSet = "FullTacticalSet",
}

export interface WorkOrder {
	job_mission_identifier: string;
	lease_duration_seconds: number;
	strategy: SearchStrategy;
	required_strata: TargetStrata;
}

export interface WorkerHeartbeat {
	worker_identifier: string;
	hostname_identity: string;
	current_hashrate: number;
	active_job_identifier?: string;
	timestamp_utc: string;
	hardware_metrics: HardwareStats;
}

export interface WorkerSnapshot {
	worker_identifier: string;
	operational_status: string;
	snapshot_base64_data: string;
	captured_at_timestamp: string;
	hardware_metrics?: HardwareStats;
}

/**
 * UNIÓN DISCRIMINADA SOBERANA (RealTimeEvent)
 * Sincronización total con el EventBus V86.0 de Rust.
 */
export type RealTimeEvent =
	| { t: "sp", p: SystemMetrics }
	| { t: "ac", p: AuditReport }
	| { t: "pl", p: ProvisioningLog }
	| { t: "bs", p: BanShieldStatus }
	| { t: "sl", p: SystemLog }
	| { t: "ir", p: SystemIntegrityReport }
	| { t: "ad", p: { drift_gap_count: number, total_tactical_count: number } }
	| { t: "cc", p: { target_bitcoin_address: string, discovery_node: string } }
	| { t: "vr", p: { worker_identifier: string, operational_status: string, system_timestamp: number } };
